language: java

jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    - "./gradlew clean build"
    - "./gradlew test"
    
before_install: 
    - "chmod +x gradlew"

notifications:
  email:
    recipients:
      - jiwoourty@gmail.com
